Adding route for Event Api
iiitv/arcadia-backend pull request #6
Opened 2021-10-02 12:05 UTC by mugdha273

2021-10-02 15:15 UTC, gaurKrishna requested changes
@mugdha273 read about [simple router](https://www.django-rest-framework.org/api-guide/routers/#simplerouter) as EventApi is a model viewset and using simple router will create the CRUD endpoints for it directly.

2021-10-03 06:32 UTC, mugdha273 commented
> @mugdha273 read about [simple router](https://www.django-rest-framework.org/api-guide/routers/#simplerouter) as EventApi is a model viewset and using simple router will create the CRUD endpoints for it directly.

I've made some changes. Please take a look.

2021-10-03 13:32 UTC, gaurKrishna approved these changes

2021-10-03 13:32 UTC, gaurKrishna approved these changes

2021-10-03 13:33 UTC, gaurKrishna commented
> > @mugdha273 read about [simple router](https://www.django-rest-framework.org/api-guide/routers/#simplerouter) as EventApi is a model viewset and using simple router will create the CRUD endpoints for it directly.
> 
> I've made some changes. Please take a look.

Looks good to me, merging your pr.

2021-10-03 13:34 UTC, merged